spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecdb?useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ec_user
    password: changeit
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080
